Adding e2e test to cluster init

diff --git a/.github/workflows/cluster-init.yaml b/.github/workflows/cluster-init.yaml
--- a/.github/workflows/cluster-init.yaml
+++ b/.github/workflows/cluster-init.yaml
@@ -51,6 +51,7 @@ jobs:
     runs-on: ubuntu-latest
     needs:
       - release-rules
+      - test-e2e
     steps:
       - uses: actions/checkout@v2
         with:
@@ -75,3 +76,71 @@ jobs:
 
       - name: Publish Cluster Init Docker Image
         run: docker push ${{ steps.build.outputs.cluster-init-image }}
+
+  test-e2e:
+    runs-on: ubuntu-latest
+    env:
+      LOCAL_REGISTRY: registry.localhost:5000
+
+    steps:
+      - name: Check out code
+        uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
+
+      - name: Build Docker image
+        id: build-image
+        working-directory: infra/cluster-init
+        run: |
+          set -o pipefail
+          make build-image | tee output.log
+          echo "::set-output name=cluster-init-version::$(sed -n 's%turing-cluster-init version: \(.*\)%\1%p' output.log)"
+
+      - name: Publish images to local registry
+        env:
+          DOCKER_REPOSITORY: ${{ env.LOCAL_REGISTRY }}/${{ github.repository }}
+          CLUSTER_INIT_VERSION: ${{ steps.build-image.outputs.cluster-init-version }}
+        run: |
+          # Cluster init
+          docker image load --input cluster-init.${{ env.CLUSTER_INIT_VERSION }}.tar
+          docker tag \
+            cluster-init:${{ env.CLUSTER_INIT_VERSION }} \
+            ${{ env.DOCKER_REPOSITORY }}/cluster-init:${{ env.CLUSTER_INIT_VERSION }}
+          docker push ${{ env.DOCKER_REPOSITORY }}/cluster-init:${{ env.CLUSTER_INIT_VERSION }}
+      
+      - name: "Setup local k8s cluster"
+        uses: AbsaOSS/k3d-action@v1.5.0
+        with:
+          cluster-name: ${{ env.CLUSTER_NAME }}
+          use-default-registry: true
+          args: >-
+            --servers 1
+            --agents 3
+            --port 80:80@loadbalancer
+            --k3s-server-arg "--no-deploy=traefik,metrics-server"
+
+      - name: "Install Infrastructure"
+        env:
+          CLUSTER_INIT_VERSION: ${{ steps.build-image.outputs.cluster-init-version }}
+        run: |
+          kubectl create ns infrastructure
+          helm upgrade turing-init infra/charts/turing-init \
+            --namespace infrastructure \
+            --set image.registry=${{ env.LOCAL_REGISTRY }}/ \
+            --set image.repository=${{ github.repository }}/cluster-init \
+            --set image.tag=${{ env.CLUSTER_INIT_VERSION }} \
+            --set knative.domains="127.0.0.1.nip.io" \
+            --set knative.registriesSkippingTagResolving=${{ env.LOCAL_REGISTRY }} \
+            --install \
+            --wait
+
+          # wait for install infra job to finish
+          kubectl logs -n infrastructure -f $(kubectl get pod --namespace infrastructure | grep -v 'NAME' | grep -v 'spark' | head -n 1 | awk '{print $1}')
+          kubectl get pod --all-namespaces
+          kubectl get svc --all-namespaces
+          kubectl wait -n infrastructure --for=condition=complete --timeout=10m job/turing-init-spark-operator-webhook-init
+          # Might fail the first time but the 2nd run should work, rarely fails on the first try though.
+          kubectl wait -n infrastructure --for=condition=complete --timeout=10m job/turing-init-init
+      
+      - name: Tear down infrastructure job
+        run: helm delete --namespace infrastructure turing-init --timeout 15m
